/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AggregatingDataSourceEditorPanel.java
 *
 * Created on Apr 22, 2009, 8:37:48 AM
 */

package org.virbo.cdfdatasource;

import gsfc.nssdc.cdf.Attribute;
import gsfc.nssdc.cdf.CDF;
import gsfc.nssdc.cdf.CDFException;
import gsfc.nssdc.cdf.Variable;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.autoplot.help.AutoplotHelpSystem;
import org.das2.util.DasExceptionHandler;
import org.das2.util.FileUtil;
import org.das2.util.filesystem.FileSystem;
import org.das2.util.monitor.ProgressMonitor;
import org.virbo.dataset.QDataSet;
import org.virbo.datasource.DataSetSelector;
import org.virbo.datasource.DataSetURI;
import org.virbo.datasource.DataSourceEditorPanel;
import org.virbo.datasource.URISplit;

/**
 *
 * @author jbf
 */
public class CdfDataSourceEditorPanel extends javax.swing.JPanel implements DataSourceEditorPanel {
    public static final String NO_PLOTTABLE_PARAMETERS_MSG = "<html><em>No plottable parameters</em></html>";

    /** the maximum number of DEPEND_1 channels where we should show option for depend_1. */
    private static final int MAX_SLICE1_OFFER = 32;

    private final static Logger logger= Logger.getLogger( "apdss.cdfn" );
    
    private boolean isValidCDF= false;

    /** Creates new form AggregatingDataSourceEditorPanel */
    public CdfDataSourceEditorPanel() {
        initComponents();
        jPanel3.setVisible(false);
        AutoplotHelpSystem.getHelpSystem().registerHelpID(this, "cdf_main");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        selectVariableLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        paramInfo = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        parameterTree = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        subsetComboBox = new javax.swing.JComboBox();
        interpretMetadataLabel = new javax.swing.JLabel();
        noInterpMeta = new javax.swing.JCheckBox();
        noDep = new javax.swing.JCheckBox();
        showAllVarTypeCB = new javax.swing.JCheckBox();
        whereCB = new javax.swing.JCheckBox();
        whereParamList = new javax.swing.JComboBox();
        whereOp = new javax.swing.JComboBox();
        whereTF = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        selectVariableLabel.setText("Select CDF Variable:");

        jSplitPane1.setDividerLocation(230);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        paramInfo.setText("Variable");
        paramInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        paramInfo.setMaximumSize(new java.awt.Dimension(1000, 4000));
        paramInfo.setPreferredSize(new java.awt.Dimension(600, 100));
        paramInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jScrollPane2.setViewportView(paramInfo);

        jSplitPane1.setBottomComponent(jScrollPane2);

        jSplitPane2.setDividerLocation(320);
        jSplitPane2.setResizeWeight(1.0);

        parameterTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                parameterTreeValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(parameterTree);

        jSplitPane2.setLeftComponent(jScrollPane3);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Advanced"));
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 32767));

        jLabel3.setText("Load subset of the data:");
        jLabel3.setToolTipText("<html>Load a subset of the data records, for example:<br>[0:100]  first 100 records<br> [-100:] last 100 records<br> [::10] every tenth record<br> </html>");

        subsetComboBox.setEditable(true);
        subsetComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "::10", "0:100", "-100:", "0:10000:5" }));
        subsetComboBox.setToolTipText("<html>Load a subset of the data records, for example:<br>[0:100]  first 100 records<br> [-100:] last 100 records<br> [::10] every tenth record<br> </html>");

        interpretMetadataLabel.setText("Interpret Metadata:");

        noInterpMeta.setText("no ISTP");
        noInterpMeta.setToolTipText("Don't interpret metadata to get titles and units.");

        noDep.setText("no dependencies");
        noDep.setToolTipText("Ignore connections between variables like \"DEPEND_0\"\n");

        showAllVarTypeCB.setText("show all");
        showAllVarTypeCB.setToolTipText("show all parameters, even if ISTP VAR_TYPE is not \"data\"");
        showAllVarTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllVarTypeCBActionPerformed(evt);
            }
        });

        whereCB.setText("Only load data where:");
        whereCB.setToolTipText("return only the records where the condition is true");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, whereTF, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), whereCB, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        whereParamList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        whereParamList.setMaximumSize(new java.awt.Dimension(100, 32767));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, whereCB, org.jdesktop.beansbinding.ELProperty.create("${selected}"), whereParamList, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        whereOp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".eq", ".gt", ".lt" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, whereCB, org.jdesktop.beansbinding.ELProperty.create("${selected}"), whereOp, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        whereTF.setText("0");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, whereCB, org.jdesktop.beansbinding.ELProperty.create("${selected}"), whereTF, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel3)
            .add(whereCB)
            .add(interpretMetadataLabel)
            .add(jPanel3Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(whereParamList, 0, 123, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(whereOp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(whereTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(1, 1, 1))
                    .add(subsetComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(showAllVarTypeCB)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(noInterpMeta)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(noDep))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(subsetComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(whereCB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(whereParamList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(whereOp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(whereTF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(interpretMetadataLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(noInterpMeta)
                    .add(noDep))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(showAllVarTypeCB)
                .addContainerGap())
        );

        jSplitPane2.setRightComponent(jPanel3);

        jSplitPane1.setTopComponent(jSplitPane2);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(selectVariableLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(selectVariableLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void showAllVarTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllVarTypeCBActionPerformed
        org.das2.util.LoggerManager.logGuiEvent(evt);    
        setURI( getURI() );
    }//GEN-LAST:event_showAllVarTypeCBActionPerformed

    private void parameterTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_parameterTreeValueChanged
        TreePath tp= evt.getPath();
        if ( isValidCDF ) {
            parameter= String.valueOf(tp.getPathComponent(1));
            updateMetadata();
        }
    }//GEN-LAST:event_parameterTreeValueChanged

    private void updateMetadata() {
       String longName= parameterInfo.get(parameter);
       paramInfo.setText( longName );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel interpretMetadataLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JCheckBox noDep;
    private javax.swing.JCheckBox noInterpMeta;
    private javax.swing.JLabel paramInfo;
    private javax.swing.JTree parameterTree;
    private javax.swing.JLabel selectVariableLabel;
    private javax.swing.JCheckBox showAllVarTypeCB;
    private javax.swing.JComboBox subsetComboBox;
    private javax.swing.JCheckBox whereCB;
    private javax.swing.JComboBox whereOp;
    private javax.swing.JComboBox whereParamList;
    private javax.swing.JTextField whereTF;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanel() {
        if (showAllInitially) {
            SwingUtilities.invokeLater( new Runnable() {
                public void run() {
                    showAllVarTypeCB.setSelected(true);
                    setURI( getURI() );
                }
            });
        }            
        return this;
    }


    JComponent delegateComponent = null;
    DataSetSelector delegateDataSetSelector=null;
    DataSourceEditorPanel delegateEditorPanel= null;
    URISplit split;
    /**
     * URI parameters
     */
    Map<String,String> params;

    /**
     * short descriptions of the parameters
     */
    Map<String,String> parameterDescriptions;

    /**
     * long descriptions html formatted metadata about each parameter.
     */
    Map<String,String> parameterInfo;

    String parameter;

    boolean showAllInitially= false;
    
    /**
     * can I reuse the slice?  Only if the maxRec doesn't change.
     */
    long subsetMaxRec=-1;

    File cdfFile;
    CDF cdf;
    CDFException cdfException;

    /**
     * allow more abstract sources, namely cdaweb, to turn off these controls.
     * @param v
     */
    public void setShowAdvancedSubpanel( boolean v ) {
        interpretMetadataLabel.setVisible(v);
        noDep.setVisible(v);
        noInterpMeta.setVisible(v);
    }

    public boolean reject( String url ) throws IOException, URISyntaxException {
        split = URISplit.parse(url);
        FileSystem fs = FileSystem.create( DataSetURI.getWebURL( DataSetURI.toUri(split.path) ).toURI() );
        if ( fs.isDirectory( split.file.substring(split.path.length()) ) ) {
            return true;
        }
        return false;
    }

    public boolean prepare( String url,  java.awt.Window parent, ProgressMonitor mon) throws Exception {
        split= URISplit.parse(url);

        cdfFile= DataSetURI.getFile( split.resourceUri.toURL(), mon );
        DataSetURI.checkLength(cdfFile);

        logger.log(Level.FINE, "opening cdf file {0}", cdfFile.toString());
        try {
            cdf= CdfFileDataSourceFactory.getCDFFile( cdfFile.toString() ); // only open the cdf once.
            cdfException= null;
        } catch ( CDFException ex ) {
            this.cdf= null;
            this.cdfException= ex;
        }

        return true;
    }

    public void setURI(String url) {
        split= URISplit.parse(url);
        params= URISplit.parseParams(split.params);

        try {

            if ( cdf==null && cdfException==null ) {
                cdf= CdfFileDataSourceFactory.getCDFFile( cdfFile.toString() ); // only open the cdf once.
            }
            
            if ( cdfException!=null ) {
                this.selectVariableLabel.setText( " " );
                this.parameterTree.setModel( new DefaultTreeModel( new DefaultMutableTreeNode("Error") ) );
                String txt= "<html>\n"+cdfException.toString();
                try {
                    String magic= FileUtil.getMagic( cdfFile );
                    if ( magic.substring(1).equals("HDF") ) {
                        txt= txt+"<br><br><p color='#FF0000'>File appears to be a HDF (or maybe NetCDF) file.</p>";
                    }
                } catch ( IOException ex ) {
                    logger.log(Level.WARNING,ex.toString(),ex);
                }
                this.paramInfo.setText( txt );
                return;
            }
            
            logger.finest("inspect cdf for plottable parameters");
            parameterDescriptions= CdfUtil.getPlottable( cdf, !showAllVarTypeCB.isSelected(), QDataSet.MAX_RANK, false );
            if ( parameterDescriptions.isEmpty() ) {
                throw new IllegalArgumentException("no plottable parameters in cdf file!");
            }
            Map<String,String> allParameterInfo= CdfUtil.getPlottable( cdf, false, QDataSet.MAX_RANK, true );
            Map<String,String> dataParameterInfo= CdfUtil.getPlottable( cdf, true, QDataSet.MAX_RANK, true );
            Map<String,String> whereParameterInfo= CdfUtil.getPlottable( cdf, false, 1, false );
            
            
            String label;
            if ( this.showAllVarTypeCB.isSelected() ) {
                parameterInfo= allParameterInfo;
                label= "Select CDF Variable (%d data, %d support):";
            } else {
                parameterInfo= dataParameterInfo;
                label= "Select CDF Variable (%d data, %d support not shown):";
            }
            
            this.isValidCDF= true;
            jPanel3.setVisible(true);
            
            int numData= dataParameterInfo.size();
            int numSupport= allParameterInfo.size() - numData;

            this.selectVariableLabel.setText( String.format( label, numData, numSupport ) );
            this.selectVariableLabel.setToolTipText("ISTP metadata marks parameters as data or support_data");

            String param= params.get("arg_0");
            String subset= null;
            if ( param!=null ) {
                int i= param.indexOf("[");
                if ( i!=-1 ) {
                    subset= param.substring(i);
                    param= param.substring(0,i);
                }
            }

            if ( allParameterInfo.containsKey(param) ) {
                if ( !dataParameterInfo.containsKey(param) ) {
                    showAllInitially= true;
                }
            }
            
            String slice1= params.remove("slice1");

            fillTree( this.parameterTree, parameterDescriptions, cdf, param, slice1 );

            logger.finest("close cdf");
            CdfFileDataSourceFactory.closeCDF(cdf);
            cdf= null;

            DefaultComboBoxModel cbmodel= new DefaultComboBoxModel();
            for ( String p: parameterDescriptions.keySet() ) {
                cbmodel.addElement(p);
            }

            //TODO: clean up below with subset...
            if ( param!=null ) {
                int i= param.indexOf("[");
                if ( i!=-1 ) {
                    subsetComboBox.setSelectedItem( param.substring(i) );
                    param= param.substring(0,i);
                } else {
                    subsetComboBox.setSelectedItem("");
                }
            } else {
                parameter= parameterDescriptions.entrySet().iterator().next().getKey();
                subsetComboBox.setSelectedItem("");
                param= parameter;
            }
            parameter= param.replaceAll("%3D", "=");

            if ( "no".equals( params.get("interpMeta")) ) {
                noInterpMeta.setSelected(true);
            }

            if ( "no".equals( params.get("doDep" ) ) ) {
                noDep.setSelected(true);
            }
            
            whereParamList.setModel( new DefaultComboBoxModel( whereParameterInfo.keySet().toArray() ) );
            String where= params.get("where");
            if ( where!=null && where.length()>0 ) {
                whereCB.setSelected(true);
                int i= where.indexOf(".");
                if ( i>-1 ) {
                    whereParamList.setSelectedItem(where.substring(0,i)); 
                    whereOp.setSelectedItem(where.substring(i,i+3) ); // DANGER assumes 3 chars
                    whereTF.setText(where.substring(i+4,where.length()-1));
                }
            } else {
                whereCB.setSelected(false);
            }

        } catch (CDFException ex) {
            DasExceptionHandler.handle( ex );
        } catch (IllegalArgumentException ex) {
            DasExceptionHandler.handle( ex );
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }

    }

    public String getURI() {
        String slice= subsetComboBox.getSelectedItem().toString().trim();
        if ( slice.length()>0 && slice.charAt(0)!='[' ) {
            slice= "["+slice+"]";
        }

        if ( isValidCDF ) {
            TreePath treePath= parameterTree.getSelectionPath();
            if ( treePath==null ) {
                logger.fine("param was null");
            } else if ( treePath.getPathCount()==3 ) {
                String p= String.valueOf( treePath.getPathComponent(1) );
                p= p.replaceAll("=", "%3D");
                params.put( "arg_0", p + ( slice==null ? "" : slice ) );
                String val=  String.valueOf( treePath.getPathComponent(2) );
                int idx= val.indexOf(":");
                params.put( "slice1", val.substring(0,idx).trim() );
            } else {
                String p= String.valueOf( treePath.getPathComponent(1) );
                p= p.replaceAll("=", "%3D");
                params.put( "arg_0", p + ( slice==null ? "" : slice ) );
            }

            if ( noDep.isSelected() ) {
                params.put("doDep","no");
            } else {
                params.remove("doDep");
            }
            if ( noInterpMeta.isSelected() ) {
                params.put("interpMeta", "no");
            } else {
                params.remove("interpMeta");
            }

            if ( whereCB.isSelected() ) {
                params.put( "where", String.format( "%s%s(%s)", whereParamList.getSelectedItem(), whereOp.getSelectedItem(), whereTF.getText() ) );
            } else {
                params.remove("where");
            }
        }
        
        split.params= URISplit.formatParams(params);
        return URISplit.format(split);
    }

    public void markProblems(List<String> problems) {
        
    }

    private void fillTree( JTree parameterTree, Map<String,String> mm, CDF cdf, String param, String slice1 ) throws CDFException {

        DefaultMutableTreeNode root= new DefaultMutableTreeNode("");

        Attribute attr= null;
        try {
            attr= cdf.getAttribute("LABL_PTR_1");
        } catch ( CDFException ex ) {
        }

        TreePath selection=null;
        for ( Entry<String,String> e: mm.entrySet() ) {
            Variable v= cdf.getVariable(e.getKey());
            gsfc.nssdc.cdf.Entry lablPtr1=null;
            try {
                if ( attr!=null ) lablPtr1= attr.getEntry(v);
            } catch ( CDFException ex ) {
            }
            boolean doComponents= lablPtr1!=null && v.getDimSizes().length==1 && v.getDimSizes()[0]<=MAX_SLICE1_OFFER;
            if ( doComponents ) {
                String s= (String) lablPtr1.getData();
                try {
                    Variable labl= cdf.getVariable(s);
                    DefaultMutableTreeNode node= new DefaultMutableTreeNode( e.getKey() );
                    Object oo= labl.getRecord(0);
                    if ( !oo.getClass().isArray() || !( String.class.isAssignableFrom( oo.getClass().getComponentType() ) ) ) {
                        logger.fine("Expected string array in element: "+s);
                        continue;
                    }
                    String[] rec= (String[]) labl.getRecord(0);
                    for ( int i=0; i<rec.length; i++ ) {
                        String snode=  String.format("%d: %s", i, rec[i] ) ;
                        DefaultMutableTreeNode child= new DefaultMutableTreeNode( snode );
                        node.add( child );
                        if ( e.getKey().equals(param) ) {
                            if ( slice1!=null ) {
                                if ( String.valueOf(i).equals(slice1) ) {
                                    selection= new TreePath( new Object[] { root, node, child } );
                                }
                            } else {
                                selection= new TreePath( new Object[] { root, node } );
                            }
                        }
                    }
                    root.add( node );
                } catch ( CDFException ex ) {
                    logger.log(Level.WARNING,"parameter name found: "+s+" referred to by " +e.getKey(),ex);
                    DefaultMutableTreeNode node= new DefaultMutableTreeNode( e.getKey() );
                    root.add( node );
                }

            } else {
                DefaultMutableTreeNode node=  new DefaultMutableTreeNode( e.getKey() );
                root.add( node );
                if ( e.getKey().equals(param) ) {
                    selection= new TreePath( new Object[] { root, node } );
                }
            }
        }

        DefaultTreeModel tm= new DefaultTreeModel( root );

        parameterTree.setRootVisible(false);
        parameterTree.setModel(tm);

        if ( selection!=null ) parameterTree.setSelectionPath(selection);

    }

}
