/*
 * MetaDataPanel.java
 *
 * Created on July 27, 2007, 11:54 AM
 */
package org.virbo.autoplot;

import edu.uiowa.physics.pw.das.datum.Datum;
import edu.uiowa.physics.pw.das.datum.DatumUtil;
import edu.uiowa.physics.pw.das.datum.Units;
import edu.uiowa.physics.pw.das.util.CombinedTreeModel;
import org.das2.util.monitor.ProgressMonitor;
import org.das2.util.monitor.NullProgressMonitor;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DecimalFormat;
import java.util.LinkedHashMap;
import javax.swing.SwingUtilities;
import javax.swing.tree.TreeModel;
import org.virbo.dataset.QDataSet;
import org.virbo.datasource.DataSource;
import org.virbo.dsutil.PropertiesTreeModel;
import org.virbo.metatree.NameValueTreeModel;

/**
 *
 * @author  jbf
 */
public class MetaDataPanel extends javax.swing.JPanel {

    ApplicationModel applicationModel;
    CombinedTreeModel tree;

    /** Creates new form MetaDataPanel */
    public MetaDataPanel(ApplicationModel applicationModel) {
        this.applicationModel = applicationModel;
        initComponents();
        metaDataTree.setModel(null);
        applicationModel.addPropertyChangeListener(this.appModelListener);
        update();
    }

    public void update() {
        tree = new CombinedTreeModel("metadata");
        try {
            DataSource dsrc = applicationModel.dataSource();
            if (dsrc != null) {
                ProgressMonitor mon = new NullProgressMonitor();
                TreeModel dsrcMeta = dsrc.getMetaData(mon);
                if (dsrcMeta != null) {
                    tree.mountTree(dsrcMeta);
                }
            }
            metaDataTree.setModel(tree);
        } catch (Exception e) {
            applicationModel.application.getExceptionHandler().handle(e);
        }
    }
    PropertyChangeListener appModelListener = new PropertyChangeListener() {

        public void propertyChange(PropertyChangeEvent evt) {
            if (evt.getPropertyName().equals(ApplicationModel.PROPERTY_FILL)) {
                updateStatistics();
            }

        }
    };

    private String format(double d) {
        if (Math.abs(Math.log(d) / Math.log(10)) < 3) {
            DecimalFormat df1 = new DecimalFormat("0.00");
            return df1.format(d);
        } else {
            DecimalFormat df = new DecimalFormat("0.00E0");
            return df.format(d);
        }
    }
    boolean statisticsDirty;

    private void updateStatistics() {
        statisticsDirty = true;
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                if (statisticsDirty) {
                    updateStatisticsImmediately();
                    updateDataSetPropertiesView();
                }
            }
        });
    }

    private void updateDataSetPropertiesView() {
        tree.mountTree( new PropertiesTreeModel("dataset= ",applicationModel.dataset) );
    }

    private synchronized void updateStatisticsImmediately() {

        QDataSet ds = applicationModel.fillDataset;
        if (ds == null) {
            // TODO: do something to indicate state
            return;
        }

        AutoplotUtil.MomentDescriptor moments = AutoplotUtil.moment(ds);

        LinkedHashMap map = new LinkedHashMap();

        map.put("# invalid", String.valueOf(moments.invalidCount) + " of " + String.valueOf(moments.validCount + moments.invalidCount));
        String s;
        if (moments.validCount > 0) {
            s = format(moments.moment[0]);
        } else {
            s = "";
        }
        map.put("Mean", s);

        if (moments.validCount > 1) {
            s = format(moments.moment[1]);
        } else {
            s = "";
        }
        map.put("Std Dev", s);

        QDataSet dep0 = (QDataSet) ds.property(QDataSet.DEPEND_0);
        assert (dep0 != null);
        Double cadence = (Double) dep0.property(QDataSet.CADENCE);

        Units xunits = (Units) dep0.property(QDataSet.UNITS);
        if (xunits == null) {
            xunits = Units.dimensionless;
        }

        Datum d = DatumUtil.asOrderOneUnits(xunits.getOffsetUnits().createDatum(cadence));
        Units u = d.getUnits();

        map.put("Cadence", format(d.doubleValue(u)) + " " + u);

        tree.mountTree(NameValueTreeModel.create("Statistics", map));

        statisticsDirty = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        metaDataTree = new javax.swing.JTree();

        metaDataTree.setShowsRootHandles(true);
        jScrollPane1.setViewportView(metaDataTree);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree metaDataTree;
    // End of variables declaration//GEN-END:variables
}
