/*
 * PlotStylePanel.java
 *
 * Created on July 27, 2007, 9:41 AM
 */

package org.virbo.autoplot;

import edu.uiowa.physics.pw.das.components.DatumEditor;
import edu.uiowa.physics.pw.das.components.propertyeditor.ColorEditor;
import edu.uiowa.physics.pw.das.components.propertyeditor.EnumerationEditor;
import edu.uiowa.physics.pw.das.components.propertyeditor.PropertyEditor;
import java.awt.BorderLayout;
import java.util.List;
import javax.beans.binding.Binding;
import javax.beans.binding.BindingContext;
import javax.beans.binding.BindingConverter;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  jbf
 */
public class PlotStylePanel extends javax.swing.JPanel {
    
    ApplicationModel applicationModel;
    
    /** Creates new form PlotStylePanel */
    public PlotStylePanel( final ApplicationModel applicationModel ) {
        this.applicationModel= applicationModel;
        
        initComponents();
        
        symSizeSpinner.setModel( new SpinnerNumberModel( 2.0f, 0.09f, 10.f, 0.2f ) );
        
        EnumerationEditor psymEditor= new EnumerationEditor();
        psymEditor.setValue( applicationModel.seriesRend.getPsym() );
        psymPanel.add(psymEditor.getCustomEditor(), BorderLayout.CENTER);
        
        EnumerationEditor lineEditor= new EnumerationEditor();
        lineEditor.setValue( applicationModel.seriesRend.getPsymConnector() );
        lineStylePanel.add(lineEditor.getCustomEditor(), BorderLayout.CENTER);
        
        lineThickSpinner.setModel( new SpinnerNumberModel( 1.0f, 0.09f, 10.f, 0.2f ) );
                
        EnumerationEditor edit= new EnumerationEditor();
        edit.setValue( applicationModel.colorbar.getType() );
        colortableTypePanel.add( edit.getCustomEditor(), BorderLayout.CENTER );
        
        EnumerationEditor rebin= new EnumerationEditor();
        rebin.setValue( applicationModel.spectrogramRend.getRebinner() );
        rebinPanel.add( rebin.getCustomEditor(), BorderLayout.CENTER );
        
        ColorEditor colorEditor= new ColorEditor();
        
        colorEditor.setValue( applicationModel.seriesRend.getColor() );
        colorPanel.add( colorEditor.getSmallEditor(), BorderLayout.CENTER );
        
        ColorEditor fillColorEditor= new ColorEditor();
        
        fillColorEditor.setValue( applicationModel.seriesRend.getFillColor() );
        fillColorPanel.add( fillColorEditor.getSmallEditor(), BorderLayout.CENTER );
                
        DatumEditor referenceEditor= new DatumEditor();
        referenceValuePanel.add(referenceEditor);
        
        validate();
        
        BindingContext bc= new BindingContext();
        Binding b;
        
        BindingConverter passThru= new BindingConverter() {
            public Object sourceToTarget(Object object) {
                return object;
            }
            public Object targetToSource( Object object ) {
                return object;
            }
        };
        
        b = bc.addBinding( applicationModel.seriesRend, "${symSize}", symSizeSpinner, "value");
        b.bind();
        
        b= bc.addBinding( applicationModel.seriesRend, "${psym}", psymEditor, "value");
        b.bind();
        
        b = bc.addBinding( applicationModel.seriesRend, "${lineWidth}", lineThickSpinner, "value");
        b.bind();
                
        b= bc.addBinding( applicationModel.seriesRend, "${psymConnector}", lineEditor, "value");
        b.bind();

        b= bc.addBinding( applicationModel.colorbar, "${type}", edit, "value" );
        b.bind();

        b= bc.addBinding( applicationModel.spectrogramRend, "${rebinner}", rebin, "value" );
        b.bind();

        b= bc.addBinding( applicationModel.seriesRend, "${color}", colorEditor, "value" );
        b.bind();

        b= bc.addBinding( applicationModel.seriesRend, "${fillToReference}", fillToReferenceCheckBox, "selected" );
        b.bind();
        
        b= bc.addBinding( applicationModel.seriesRend, "${fillColor}", fillColorEditor, "value" );
        b.bind();
                
        b= bc.addBinding( applicationModel.seriesRend, "${reference}", referenceEditor, "value" );
        b.bind();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        colortableTypePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rebinPanel = new javax.swing.JPanel();
        moreSprectrogramPropsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lineThickSpinner = new javax.swing.JSpinner();
        symSizeSpinner = new javax.swing.JSpinner();
        colorPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        moreSeriesPropsButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fillColorPanel = new javax.swing.JPanel();
        fillToReferenceCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        referenceValuePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        psymPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lineStylePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("spectrogram"));

        colortableTypePanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("colortable:");

        jLabel5.setText("rebin:");

        rebinPanel.setLayout(new java.awt.BorderLayout());

        moreSprectrogramPropsButton.setText("more...");
        moreSprectrogramPropsButton.setToolTipText("bring up property sheet with all properties for the spectrogram renderer.");
        moreSprectrogramPropsButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        moreSprectrogramPropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreSprectrogramPropsButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rebinPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(colortableTypePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(moreSprectrogramPropsButton)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(colortableTypePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel5)
                    .add(rebinPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(moreSprectrogramPropsButton)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {colortableTypePanel, rebinPanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("symbol line"));

        jLabel3.setText("line thickness:");

        jLabel2.setText("symbol size:");

        colorPanel.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("color:");

        moreSeriesPropsButton.setText("more...");
        moreSeriesPropsButton.setToolTipText("bring up property sheet with all properties for the series renderer.");
        moreSeriesPropsButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        moreSeriesPropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreSeriesPropsButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("fill color:");

        fillColorPanel.setLayout(new java.awt.BorderLayout());

        fillToReferenceCheckBox.setText("fill to reference");
        fillToReferenceCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jLabel8.setText("reference value:");

        referenceValuePanel.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("plot symbol:");

        psymPanel.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("line style:");

        lineStylePanel.setLayout(new java.awt.BorderLayout());

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(referenceValuePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .add(jPanel2Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(fillToReferenceCheckBox)
                .addContainerGap(168, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(moreSeriesPropsButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel9)
                                    .add(jLabel6)
                                    .add(jLabel2)
                                    .add(jLabel3)
                                    .add(jLabel10)))
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(jLabel7)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(fillColorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .add(lineThickSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lineStylePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(symSizeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(psymPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(colorPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {colorPanel, lineStylePanel, psymPanel}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, colorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(psymPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(symSizeSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel10)
                    .add(lineStylePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(lineThickSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fillToReferenceCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(fillColorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(referenceValuePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(moreSeriesPropsButton)
                .add(12, 12, 12))
        );

        jPanel2Layout.linkSize(new java.awt.Component[] {fillColorPanel, jLabel7}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel2Layout.linkSize(new java.awt.Component[] {jLabel10, jLabel3, lineStylePanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jPanel2Layout.linkSize(new java.awt.Component[] {jLabel2, jLabel6, jLabel9, psymPanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        jLabel1.setText("Plot Style");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabel1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {jPanel1, jPanel2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void moreSprectrogramPropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreSprectrogramPropsButtonActionPerformed
        new PropertyEditor(applicationModel.spectrogramRend).showDialog(this);
    }//GEN-LAST:event_moreSprectrogramPropsButtonActionPerformed

    private void moreSeriesPropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreSeriesPropsButtonActionPerformed
        new PropertyEditor(applicationModel.seriesRend).showDialog(this);
    }//GEN-LAST:event_moreSeriesPropsButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorPanel;
    private javax.swing.JPanel colortableTypePanel;
    private javax.swing.JPanel fillColorPanel;
    private javax.swing.JCheckBox fillToReferenceCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel lineStylePanel;
    private javax.swing.JSpinner lineThickSpinner;
    private javax.swing.JButton moreSeriesPropsButton;
    private javax.swing.JButton moreSprectrogramPropsButton;
    private javax.swing.JPanel psymPanel;
    private javax.swing.JPanel rebinPanel;
    private javax.swing.JPanel referenceValuePanel;
    private javax.swing.JSpinner symSizeSpinner;
    // End of variables declaration//GEN-END:variables
    
}
