/*
 * JDiskHogPanel.java
 *
 * Created on August 20, 2008, 8:21 AM
 */

package com.cottagesystems.jdiskhog;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.AbstractAction;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTree;
import javax.swing.tree.TreePath;

/**
 *
 * @author  jbf
 */
public class JDiskHogPanel extends javax.swing.JPanel {

    /** Creates new form JDiskHogPanel */
    public JDiskHogPanel() {
        initComponents();
        jTree1.addMouseListener( createMouseListener(jTree1) );
        
    }

    private MouseListener createMouseListener(final JTree jtree) {
        return new MouseAdapter() {

            TreePath context;

            @Override
            public void mousePressed(MouseEvent e) {
                
                if (e.isPopupTrigger()) {
                    context = jtree.getPathForLocation(e.getX(), e.getY());
                    jtree.getSelectionModel().addSelectionPath(context);
                    if (context != null) {
                        showPopup(e);
                    }
                }
            }
            JPopupMenu popup;

            private void showPopup(MouseEvent e) {
                if (popup == null) {
                    popup = new JPopupMenu();
                    popup.add( new JMenuItem( new AbstractAction("Delete") {

                        public void actionPerformed(ActionEvent e) {
                            FSTreeModel model = (FSTreeModel) jtree.getModel();
                            
                            TreePath[] paths= jtree.getSelectionPaths();
                            
                            boolean okay= true;
                            IllegalArgumentException ex=null;
                            
                            for ( int i=0; i<paths.length; i++ ) {
                                File f = model.getFile(paths[i]);
                                
                                if ( f.equals(model.root) ) continue;
                                if (f.isFile()) {
                                    okay = f.delete();
                                } else {
                                    try {
                                        okay = Util.deleteFileTree(f);
                                    } catch ( IllegalArgumentException ex1 ) {
                                        ex= ex1;
                                        okay= false;
                                    }
                                }
                            }
                            
                            if (!okay) {
                                JOptionPane.showConfirmDialog(jtree, ex.getLocalizedMessage(),"unable to delete", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE );
                            }

                            scan(model.root);

                        }
                    }));
                }
                popup.show(jtree, e.getX(), e.getY());
            }
        };
    }

    public void scan( File root ) {
        DiskUsageModel dumodel = new DiskUsageModel();
        dumodel.search(root, 0, this.progressMonitorComponent1 );
        FSTreeModel model = new FSTreeModel(dumodel, root);
        jTree1.setModel(model);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        progressMonitorComponent1 = new com.cottagesystems.jdiskhog.ProgressMonitorComponent();

        setName("Form"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTree1.setName("jTree1"); // NOI18N
        jScrollPane2.setViewportView(jTree1);

        progressMonitorComponent1.setToolTipText("progress monitor"); // NOI18N
        progressMonitorComponent1.setName("progressMonitorComponent1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
            .addComponent(progressMonitorComponent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressMonitorComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private com.cottagesystems.jdiskhog.ProgressMonitorComponent progressMonitorComponent1;
    // End of variables declaration//GEN-END:variables

}
