/*
 * JDiskHogPanel.java
 *
 * Created on August 26, 2008, 4:35 PM
 */
package com.cottagesystems.jdiskhog;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTree;
import javax.swing.tree.TreePath;
import org.das2.util.monitor.NullProgressMonitor;
import org.virbo.autoplot.AutoPlotUI;

/**
 *
 * @author  jbf
 */
public class JDiskHogPanel extends javax.swing.JPanel {

    AutoPlotUI app;

    /** Creates new form JDiskHogPanel */
    public JDiskHogPanel(AutoPlotUI model) {
        this.app = model;
        initComponents();
        jTree1.addMouseListener(createMouseListener(jTree1));

    }

    private MouseListener createMouseListener(final JTree jtree) {
        return new MyMouseListener(jtree, this);
    }

    Action getDeleteAction(final JTree jtree) {
        return new AbstractAction("Delete") {

            public void actionPerformed(ActionEvent e) {
                FSTreeModel model = (FSTreeModel) jtree.getModel();

                TreePath[] paths = jtree.getSelectionPaths();

                boolean okay = true;
                IllegalArgumentException ex = null;

                for (int i = 0; i < paths.length; i++) {
                    File f = model.getFile(paths[i]);

                    if (f.equals(model.root)) {
                        continue;
                    }
                    if (f.isFile()) {
                        okay = f.delete();
                    } else {
                        try {
                            okay = Util.deleteFileTree(f);
                        } catch (IllegalArgumentException ex1) {
                            ex = ex1;
                            okay = false;
                        }
                    }
                }

                if (!okay) {
                    JOptionPane.showConfirmDialog(jtree, ex.getLocalizedMessage(), "unable to delete", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE);
                }

                scan(model.root);

            }
        };
    }

    Action getPlotAction(final JTree jtree) {
        return new AbstractAction("Plot") {

            public void actionPerformed(ActionEvent e) {

                FSTreeModel model = (FSTreeModel) jtree.getModel();

                TreePath[] paths = jtree.getSelectionPaths();


                if (paths.length == 0) return;

                File f = model.getFile(paths[0]);
                app.plotUri(f.toString());

            }
        };
    }

    Action getCopyToAction(final JTree jtree) {
        return new AbstractAction("Copy To...") {

            public void actionPerformed(ActionEvent e) {
                JFileChooser chooser = new JFileChooser();
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                if (chooser.showOpenDialog(jtree) == JFileChooser.APPROVE_OPTION) {
                    File destdir = chooser.getSelectedFile();

                    FSTreeModel model = (FSTreeModel) jtree.getModel();

                    TreePath[] paths = jtree.getSelectionPaths();

                    for (int i = 0; i < paths.length; i++) {
                        File f = model.getFile(paths[i]);
                        try {
                            Util.fileCopy(f, destdir);
                        } catch (FileNotFoundException ex1) {
                            Logger.getLogger(JDiskHogPanel.class.getName()).log(Level.SEVERE, null, ex1);
                            JOptionPane.showMessageDialog(jtree, "File Not Found:\n" + ex1.getLocalizedMessage());
                        } catch (IOException ex1) {
                            Logger.getLogger(JDiskHogPanel.class.getName()).log(Level.SEVERE, null, ex1);
                            JOptionPane.showMessageDialog(jtree, "Error Occurred:\n" + ex1.getLocalizedMessage());
                        }
                    }

                }

            }
        };
    }

    public void scan(File root) {
        DiskUsageModel dumodel = new DiskUsageModel();
        dumodel.search(root, 0, new NullProgressMonitor());
        FSTreeModel model = new FSTreeModel(dumodel, root);
        jTree1.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        jScrollPane2.setViewportView(jTree1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
