/*
 * AsciiTableModelTest.java
 *
 * Created on November 30, 2008, 7:52 PM
 */

package org.virbo.ascii;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.virbo.dsutil.AsciiParser;


/**
 *
 * @author  jbf
 */
public class AsciiTableModelTest extends javax.swing.JPanel {

    /** Creates new form AsciiTableModelTest */
    public AsciiTableModelTest() {
        try {
            initComponents();
            AsciiTableTableModel model = new AsciiTableTableModel();
            model.setFile(new File("/media/mini/data.backup/examples/dat/A1050412.small.TXT"));
            AsciiParser parser = new AsciiParser();
            AsciiParser.RecordParser recp = parser.guessDelimParser("1 2 3 4");
            model.setRecParser(recp);
            
            this.jTable1.setModel(model);
        } catch (IOException ex) {
            Logger.getLogger(AsciiTableModelTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main( String[] args ) {
        JFrame frame= new JFrame();
        frame.getContentPane().add(new AsciiTableModelTest());
        frame.pack();
        frame.setVisible(true);
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
