/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BindToHiddenDialog.java
 *
 * Created on Jul 19, 2010, 11:45:04 AM
 */

package org.autoplot;

/**
 *
 * @author jbf
 */
public class BindToHiddenDialog extends javax.swing.JPanel {

    /** Creates new form BindToHiddenDialog */
    public BindToHiddenDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        xAxisCB = new javax.swing.JCheckBox();
        yAxisCB = new javax.swing.JCheckBox();
        zAxisCB = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        condenseXAxisLabelsCB = new javax.swing.JCheckBox();
        condenseColorBarsCB = new javax.swing.JCheckBox();

        xAxisCB.setText("X Axis");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, condenseXAxisLabelsCB, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), xAxisCB, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        yAxisCB.setSelected(true);
        yAxisCB.setText("Y Axis");

        zAxisCB.setText("Z Axis (color bar)");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, condenseColorBarsCB, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), zAxisCB, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Add a hidden plot and from selected plots bind:");

        condenseXAxisLabelsCB.setText("Condense X-Axis Labels");

        condenseColorBarsCB.setText("Condense Color Bars");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(xAxisCB)
                    .add(yAxisCB)
                    .add(zAxisCB)
                    .add(condenseXAxisLabelsCB)
                    .add(condenseColorBarsCB))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xAxisCB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(yAxisCB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(zAxisCB)
                .add(18, 18, 18)
                .add(condenseXAxisLabelsCB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(condenseColorBarsCB)
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox condenseColorBarsCB;
    private javax.swing.JCheckBox condenseXAxisLabelsCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox xAxisCB;
    private javax.swing.JCheckBox yAxisCB;
    private javax.swing.JCheckBox zAxisCB;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the condenseXAxisLabelsCB
     */
    public javax.swing.JCheckBox getCondenseXAxisLabelsCB() {
        return condenseXAxisLabelsCB;
    }

    /**
     * @return the xAxisCB
     */
    public javax.swing.JCheckBox getxAxisCB() {
        return xAxisCB;
    }

    /**
     * @return the yAxisCB
     */
    public javax.swing.JCheckBox getyAxisCB() {
        return yAxisCB;
    }

    /**
     * @return the zAxisCB
     */
    public javax.swing.JCheckBox getzAxisCB() {
        return zAxisCB;
    }

    /**
     * @return the condenseColorBarsCB
     */
    public javax.swing.JCheckBox getCondenseColorBarsCB() {
        return condenseColorBarsCB;
    }

}
