/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PngWalkTool.java
 *
 * Created on Apr 29, 2009, 3:17:56 AM
 */

package org.autoplot.pngwalk;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.regex.Pattern;
import javax.swing.AbstractAction;
import org.autoplot.pngwalk.PngWalkCanvas.DisplayMode;

/**
 *
 * @author jbf
 */
public class PngWalkTool extends javax.swing.JPanel {

    PngWalkCanvas canvas;

    Pattern actionMatch=null;
    String actionCommand=null;

    /** Creates new form PngWalkTool */
    public PngWalkTool() {
        initComponents();
        canvas= new PngWalkCanvas();
        pngsPanel.add( canvas );
        canvas.addPropertyChangeListener( PngWalkCanvas.PROP_CURRENTITEM, new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                String item= canvas.getCurrentItem();
                boolean actionEnabled= actionMatch!=null && actionMatch.matcher(item).matches();
                addFileActionButton.setEnabled(actionEnabled);
                if ( actionEnabled ) {
                    addFileActionButton.setActionCommand(actionCommand+" "+item);
                }
            }
        });
    }

    public void setTemplate( String template ) {
        templateTextField.setText(template);
        canvas.setTemplate(template);
    }

    public String getTemplate() {
        return canvas.getTemplate();
    }

    void addFileAction( String match, String actionCommand, AbstractAction abstractAction ) {
        actionMatch= Pattern.compile(match);
        this.actionCommand= actionCommand;
        addFileActionButton.setAction(abstractAction);
    }

    String getSelectedFile() {
        return canvas.getCurrentItem();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pngsPanel = new javax.swing.JPanel();
        templateTextField = new javax.swing.JTextField();
        timeFilterTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        prevSetButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        scaleComboBox = new javax.swing.JComboBox();
        nextButton = new javax.swing.JButton();
        nextSetButton = new javax.swing.JButton();
        addFileActionButton = new javax.swing.JButton();

        pngsPanel.setLayout(new java.awt.BorderLayout());

        templateTextField.setText("jTextField1");
        templateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateTextFieldActionPerformed(evt);
            }
        });
        templateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                templateTextFieldFocusLost(evt);
            }
        });

        timeFilterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeFilterTextFieldActionPerformed(evt);
            }
        });
        timeFilterTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                timeFilterTextFieldFocusLost(evt);
            }
        });

        jLabel1.setText("Display Only:");
        jLabel1.setToolTipText("Enter a time range, such as \"2009\" or \"May 2009\" to limit the images displayed.");

        prevSetButton.setText("<<<");
        prevSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevSetButtonActionPerformed(evt);
            }
        });

        prevButton.setText("<");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        scaleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-Up", "7-Up", "35-Up", "CoverFlow" }));
        scaleComboBox.setSelectedIndex(1);
        scaleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleComboBoxActionPerformed(evt);
            }
        });

        nextButton.setText(">");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        nextSetButton.setText(">>>");
        nextSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextSetButtonActionPerformed(evt);
            }
        });

        addFileActionButton.setText("----");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(prevSetButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(prevButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scaleComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(nextButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nextSetButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 167, Short.MAX_VALUE)
                .add(addFileActionButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(prevButton)
                .add(nextButton)
                .add(nextSetButton)
                .add(scaleComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(prevSetButton)
                .add(addFileActionButton))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {addFileActionButton, nextButton, nextSetButton, prevButton, prevSetButton, scaleComboBox}, org.jdesktop.layout.GroupLayout.VERTICAL);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(timeFilterTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(templateTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pngsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(pngsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(templateTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(timeFilterTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scaleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleComboBoxActionPerformed
        nextSetButton.setEnabled(true);
        prevSetButton.setEnabled(true);
        switch ( scaleComboBox.getSelectedIndex() ) {
            case 0:
                canvas.setMode( DisplayMode.day );
                nextSetButton.setEnabled(false);
                prevSetButton.setEnabled(false);
                break;
            case 1:
                canvas.setMode( DisplayMode.week );
                break;
            case 2:
                canvas.setMode( DisplayMode.month );
                break;
            case 3:
                canvas.setMode( DisplayMode.coverFlow );
                break;
            default:
                throw new IllegalArgumentException("bad index");

        }
    }//GEN-LAST:event_scaleComboBoxActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        canvas.setCurrentIndex( canvas.getCurrentIndex() + 1 );
}//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        canvas.setCurrentIndex( canvas.getCurrentIndex() - 1 );
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextSetButtonActionPerformed
        canvas.setCurrentIndex( canvas.getCurrentIndex() + canvas.getCount() );
}//GEN-LAST:event_nextSetButtonActionPerformed

    private void prevSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevSetButtonActionPerformed
        canvas.setCurrentIndex( canvas.getCurrentIndex() - canvas.getCount() );
}//GEN-LAST:event_prevSetButtonActionPerformed

    private void templateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_templateTextFieldFocusLost
        String template= templateTextField.getText();
        if ( ! canvas.getTemplate().equals(template) ) {
            canvas.setTemplate(template);
        }
    }//GEN-LAST:event_templateTextFieldFocusLost

    private void templateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templateTextFieldActionPerformed
        String template= templateTextField.getText();
        if ( ! canvas.getTemplate().equals(template) ) {
            canvas.setTemplate(template);
        }
    }//GEN-LAST:event_templateTextFieldActionPerformed

    private void timeFilterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeFilterTextFieldActionPerformed
        canvas.setTimeRange( timeFilterTextField.getText() );
        if ( !canvas.getTimeRange().equals(timeFilterTextField.getText() ) ) {
            timeFilterTextField.setBackground( Color.PINK );
        } else {
            timeFilterTextField.setBackground( templateTextField.getBackground() );
        }
    }//GEN-LAST:event_timeFilterTextFieldActionPerformed

    private void timeFilterTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timeFilterTextFieldFocusLost
        canvas.setTimeRange( timeFilterTextField.getText() );
        if ( !canvas.getTimeRange().equals(timeFilterTextField.getText() ) ) {
            timeFilterTextField.setBackground( Color.PINK );
        } else {
            timeFilterTextField.setBackground( templateTextField.getBackground() );
        }
    }//GEN-LAST:event_timeFilterTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileActionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton nextSetButton;
    private javax.swing.JPanel pngsPanel;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton prevSetButton;
    private javax.swing.JComboBox scaleComboBox;
    private javax.swing.JTextField templateTextField;
    private javax.swing.JTextField timeFilterTextField;
    // End of variables declaration//GEN-END:variables

}
