/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JythonEditorPanel.java
 *
 * Created on Jul 14, 2009, 10:44:41 AM
 */

package org.virbo.datasource.jython;

import java.awt.Dimension;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.BadLocationException;
import org.das2.util.monitor.NullProgressMonitor;
import org.das2.util.monitor.ProgressMonitor;
import org.virbo.datasource.DataSetSelector;
import org.virbo.datasource.DataSetURI;
import org.virbo.datasource.DataSourceEditorPanel;
import org.virbo.datasource.URISplit;
import org.virbo.jythonsupport.JythonUtil;
import org.virbo.jythonsupport.ui.EditorAnnotationsSupport;
import org.virbo.jythonsupport.ui.ScriptPanelSupport;

/**
 *
 * @author jbf
 */
public class JythonEditorPanel extends javax.swing.JPanel implements DataSourceEditorPanel {

    ScriptPanelSupport support;
    String suri;
    File file;
    URI resourceUri;
    boolean hasVariables= false;
    List<JComponent> tflist;
    List<String> paramsList;
    List<String> deftsList;
    List<Character> typesList;  // only 'A' and 'F' right now

    /** Creates new form JythonEditorPanel */
    public JythonEditorPanel() {
        initComponents();
        tearoffTabbedPane1.hideMouseAdapter();

        support= new ScriptPanelSupport(textArea);
        support.addCaretLabel(caretPositionLabel);
        support.addFileLabel(fileNameLabel);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(12); //TODO: should be font height

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        variableComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tearoffTabbedPane1 = new org.das2.components.TearoffTabbedPane();
        scriptPanel = new javax.swing.JPanel();
        caretPositionLabel = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        textArea = new org.virbo.jythonsupport.ui.EditorTextPane();
        paramsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        variableComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(running script)" }));

        jLabel1.setText("Select variable:");
        jLabel1.setToolTipText("The dataset pointed to by the URI");

        caretPositionLabel.setText("1,1");

        fileNameLabel.setMinimumSize(new java.awt.Dimension(200, 16));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(textArea, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout scriptPanelLayout = new org.jdesktop.layout.GroupLayout(scriptPanel);
        scriptPanel.setLayout(scriptPanelLayout);
        scriptPanelLayout.setHorizontalGroup(
            scriptPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scriptPanelLayout.createSequentialGroup()
                .add(fileNameLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(caretPositionLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        scriptPanelLayout.setVerticalGroup(
            scriptPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, scriptPanelLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scriptPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(fileNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(caretPositionLabel)))
        );

        tearoffTabbedPane1.addTab("script", scriptPanel);

        paramsPanel.setLayout(new javax.swing.BoxLayout(paramsPanel, javax.swing.BoxLayout.Y_AXIS));
        tearoffTabbedPane1.addTab("params", paramsPanel);

        jLabel2.setText("Select from the variables calculated by the script, 'data' or 'result' is used by default:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(variableComboBox, 0, 440, Short.MAX_VALUE))
            .add(tearoffTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(jLabel2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(tearoffTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .add(2, 2, 2)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(variableComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel caretPositionLabel;
    protected javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paramsPanel;
    private javax.swing.JPanel scriptPanel;
    private org.das2.components.TearoffTabbedPane tearoffTabbedPane1;
    private org.virbo.jythonsupport.ui.EditorTextPane textArea;
    private javax.swing.JComboBox variableComboBox;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanel() {
        return this;
    }

    private boolean doVariables( File f, Map<String,String> params ) {

        Map<String,JythonUtil.Param> parms;

        boolean hasVars= false;
        tflist= new ArrayList();
        paramsList= new ArrayList();
        deftsList= new ArrayList();
        typesList= new ArrayList();
        
        try {
            parms= JythonDataSourceFactory.getParams( f.toURI(), new NullProgressMonitor() );

            paramsPanel.add( new JLabel("<html>This script has the following input parameters.  Buttons on the right show default values.<br><br></html>") );

            for ( Entry<String,JythonUtil.Param> e: parms.entrySet() ) {
                //String s= e.getKey();
                JythonUtil.Param parm= e.getValue();
                
                String vname= parm.name;                
                String label= parm.label;

                if ( parm.doc==null ) {
                    label= vname+ ":";
                } else {
                    String doc= parm.doc;
                    if ( doc.startsWith("'") ) doc= doc.substring(1,doc.length()-1);// pop off the quotes
                    if ( !parm.label.equals(parm.name) ) {
                        doc= doc + " ("+parm.label+" internally)";
                    }
                    label= "<html>" + parm.name + ", <em>" + doc + "</em>:</html>";
                }      
                
                
                JLabel l= new JLabel( label );
                l.setAlignmentX( JComponent.LEFT_ALIGNMENT );
                paramsPanel.add( l );

                JPanel valuePanel= new JPanel(  );
                valuePanel.setLayout( new BoxLayout( valuePanel, BoxLayout.X_AXIS ) );

                JComponent ctf= null;

                if ( parm.type=='R' ) {

                    String val= params.get(vname);
                    if ( val!=null ) {
                        if ( val.startsWith("'") ) val= val.substring(1);
                        if ( val.endsWith("'") ) val= val.substring(0,val.length()-1);
                    } else {
                        val= String.valueOf( parm.deft );
                    }

                    final String fval= val;

                    final JTextField tf= new JTextField(50);
                    Dimension x= tf.getPreferredSize();
                    x.width= Integer.MAX_VALUE;
                    tf.setMaximumSize(x);
                    tf.setUI( tf.getUI() ); // kludge to maybe avoid deadlock.

                    Icon fileIcon= new javax.swing.ImageIcon( getClass().getResource("/org/virbo/datasource/jython/file2.png"));
                    JButton filesButton= new JButton( fileIcon );
                    filesButton.addActionListener( new ActionListener() {
                        public void actionPerformed(ActionEvent e) {
                            JFileChooser c= new JFileChooser();
                            URISplit split2= URISplit.parse(fval);
                            if ( split2.scheme.equals("file") ) {
                                c.setSelectedFile( new File( split2.file.substring(7)) );
                            }
                            int r= c.showOpenDialog(jLabel1);
                            if ( r==JFileChooser.APPROVE_OPTION) {
                                tf.setText("file://"+c.getSelectedFile().toString());
                            }
                        }
                    });
                    tf.setAlignmentX( JComponent.LEFT_ALIGNMENT );

                    tf.setText( val );
                    ctf= tf;
                    valuePanel.add( ctf );
                    filesButton.setAlignmentX( JComponent.LEFT_ALIGNMENT );
                    valuePanel.add( filesButton );

                } else {
                    String val;
                    if ( params.get(vname)!=null ) {
                        val= params.get(vname);
                        if ( val.startsWith("'") ) val= val.substring(1);
                        if ( val.endsWith("'") ) val= val.substring(0,val.length()-1);
                    } else {
                        val= String.valueOf( parm.deft );
                    }
                    if ( parm.enums!=null && parm.enums.size()>0 ) {
                        JComboBox jcb= new JComboBox(parm.enums.toArray());
                        jcb.setEditable(false);
                        jcb.setSelectedItem(val);
                        ctf= jcb;
                        Dimension x= ctf.getPreferredSize();
                        x.width= Integer.MAX_VALUE;
                        ctf.setMaximumSize(x);
                        ctf.setAlignmentX( JComponent.LEFT_ALIGNMENT );
                        
                    } else {
                        JTextField tf= new JTextField(50);
                        Dimension x= tf.getPreferredSize();
                        x.width= Integer.MAX_VALUE;
                        tf.setMaximumSize(x);
                        tf.setAlignmentX( JComponent.LEFT_ALIGNMENT );

                        tf.setText( val );
                        ctf= tf;
                    }
                    
                    valuePanel.add( ctf );
                }
                

                final String fdeft= parm.type=='R' ? "default" : String.valueOf(parm.deft);
                final String fvalue= String.valueOf(parm.deft);
                final JComponent ftf= ctf;
                JButton defaultButton= new JButton( new AbstractAction( fdeft ) {
                    public void actionPerformed( ActionEvent e ) {
                        if ( ftf instanceof DataSetSelector ) {
                            ((DataSetSelector)ftf).setValue(fvalue);
                        } else if ( ftf instanceof JComboBox ) {
                            JComboBox jcb= ((JComboBox)ftf);
                            for ( int i=0; i<jcb.getItemCount(); i++ ) {
                                if ( fvalue.toString().equals( jcb.getItemAt(i).toString() ) ) {
                                    jcb.setSelectedIndex(i);
                                }
                            }
                        } else {
                            ((JTextField)ftf).setText(fvalue);
                        }
                    }
                });
                defaultButton.setToolTipText( ( parm.type == 'R' ) ? String.valueOf(parm.deft) : "Click to reset to default" );
                valuePanel.add( defaultButton );
                valuePanel.setAlignmentX( JComponent.LEFT_ALIGNMENT );
                
                paramsPanel.add( valuePanel );
                tflist.add(ctf);

                paramsList.add( parm.name );
                deftsList.add( String.valueOf( parm.deft ) );
                typesList.add( parm.type );

                hasVars= true;
            }
                
            hasVars= parms.size()>0;

            if ( !hasVars ) {
                paramsPanel.add( new JLabel("<html><em>no input parameters</em></html>") );
            }

            paramsPanel.add( Box.createVerticalGlue() );
            paramsPanel.revalidate();

        } catch (IOException ex) {
            Logger.getLogger(JythonEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return hasVars;

    }

    private String[] getScriptURI( URISplit split ) {
        Map<String,String> params= URISplit.parseParams(split.params);

        String furi;
        String resourceUri1=null;
        if ( params.containsKey("script") ) {
            furi= params.get("script");
            resourceUri1= split.resourceUri==null ? null : split.resourceUri.toString();
        } else {
            furi= split.resourceUri.toString();
            resourceUri1= null;
        }

        return new String[] { furi, resourceUri1 };
            
    }

    public void setURI(String url) {
        try {
            this.suri= url;
            URISplit split= URISplit.parse(suri);

            String[] furir= getScriptURI( split );
            File f = DataSetURI.getFile( furir[0], new NullProgressMonitor() );

            support.loadFile(f);
            Map<String,String> results= JythonDataSourceFactory.getResultParameters( f.toString(), new NullProgressMonitor() );
            String[] dropList= new String[results.size()+1];
            int i=0;
            int idx= -1;

            Map<String,String> params= URISplit.parseParams(split.params);

            String param= params.remove("arg_0");

            dropList[0]= "";
            for ( Entry<String,String> ent: results.entrySet()  ) {
                dropList[i+1]= ent.getKey()+":  "+ent.getValue();
                if ( param!=null && param.equals(ent.getKey()) ) {
                    idx= i+1;
                }
                i++;
            }
            variableComboBox.setModel( new DefaultComboBoxModel( dropList ) );
            if ( idx>=0 ) {
                variableComboBox.setSelectedIndex(idx);
            } else {
                variableComboBox.setSelectedIndex(0);
            }

            Map<String,String> ffparams= new HashMap( params );

            if ( furir[1]!=null ) ffparams.put( "resourceURI", furir[1] );
            hasVariables= doVariables( f,ffparams );

            if ( hasVariables ) {
                tearoffTabbedPane1.setSelectedIndex(1);
            }

            List<String> errs= new ArrayList();
            if ( JythonUtil.pythonLint( f.toURI(), errs) ) {
                EditorAnnotationsSupport esa= textArea.getEditorAnnotationsSupport();
                for ( String s: errs ) {
                    String[] ss= s.split(":",2);
                    try {
                        String doc= ss[1];
                        doc= doc.replaceAll("<", "&lt;");
                        doc= doc.replaceAll(">", "&gt;");
                        esa.annotateLine(Integer.parseInt(ss[0]), EditorAnnotationsSupport.ANNO_WARNING, "variable is defined before execution: " + doc);
                    } catch (BadLocationException ex) {
                        Logger.getLogger(JythonEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }



        } catch (IOException ex) {
            Logger.getLogger(JythonEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public String getURI() {
        URISplit split=  URISplit.parse(suri);

        Map<String,String> params= URISplit.parseParams(split.params);

        String param= (String)variableComboBox.getSelectedItem();
        int i= param.indexOf(":");
        if ( i==-1 ) {
            params.put( "arg_0", param.trim() );
        } else {
            params.put( "arg_0", param.substring(0,i).trim() );
        }

        for ( int j=0; j<paramsList.size(); j++ ) {
            String name= paramsList.get(j);
            JComponent jc= tflist.get(j);
            String value;
            if ( jc instanceof JTextField ) {
                value= ((JTextField)jc).getText();
            } else if ( jc instanceof DataSetSelector ) {
                value= ((DataSetSelector)jc).getValue();
            } else if ( jc instanceof JComboBox ) {
                value= String.valueOf( ((JComboBox)jc).getSelectedItem() );
            } else {
                throw new IllegalArgumentException("the code needs attention: component for "+name+" not supported ");
            }
            
            String deft= deftsList.get(j);
            char type= typesList.get(j);

            if ( !value.equals(deft) || params.containsKey(name) ) {
                if ( type=='A' ) {
                    value= value.replaceAll("\'", "");
                    if ( !( value.startsWith("'") && value.endsWith("'") ) ) {
                        value=  "'" + value + "'";
                    }
                    params.put( name, value );
                } else if ( type=='R' ) {
                    URISplit ruriSplit= URISplit.parse(value);
                    if ( !params.containsKey("script") ) {
                        params.put( "script", split.resourceUri.toString() );
                    }
                    split.resourceUri= ruriSplit.resourceUri;
                    split.scheme= ruriSplit.scheme;
                    split.authority= ruriSplit.authority;
                    split.path= ruriSplit.path;
                    split.file= ruriSplit.file;
                    if ( split.vapScheme==null ) split.vapScheme= "vap+jyds";
                } else {
                    params.put( name, value );
                }
            } else if ( type=='R' && value.equals(deft) && ( split.resourceUri==null || !split.resourceUri.toString().equals(deft) ) ) {
                URISplit ruriSplit= URISplit.parse(value); //TODO: consider removing script=param.
                if (params.get("script")==null ) {
                    params.put( "script", split.resourceUri.toString() );
                }
                split.resourceUri= ruriSplit.resourceUri;
                split.scheme= ruriSplit.scheme;
                split.authority= ruriSplit.authority;
                split.path= ruriSplit.path;
                split.file= ruriSplit.file;
                if ( split.vapScheme==null ) split.vapScheme= "vap+jyds"; // DANGER--this ought-not to be hard coded, but this is all I can do for now...
            }
        }

        split.params= URISplit.formatParams(params);

        if ( support.isDirty() ) {
            try {
                FileWriter writer = new FileWriter(support.getFile());
                writer.write( textArea.getText() );
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(JythonEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return URISplit.format(split);
    }

    public boolean reject(String uri) throws Exception {
        URISplit split= URISplit.parse(uri);
        if ( split.file==null || split.file.length()==0 || split.file.equals("file:///") ) {
            Map<String,String> params= URISplit.parseParams(split.params);
            if ( params.containsKey("script") ) {
                return false;
            } else {
                return true;
            }
        } else {
            return false;
        }
    }


    public boolean prepare(String uri, Window parent, ProgressMonitor mon) throws Exception {

        URISplit split= URISplit.parse(uri);
        String[] furir= getScriptURI( split );
        DataSetURI.getFile( furir[0], mon );
        return true;
    }

}
