/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.autoplot.pdsppi;

import java.awt.Window;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import org.das2.util.LoggerManager;
import org.das2.util.filesystem.FSTreeModel;
import org.das2.util.filesystem.FileSystem;
import org.das2.util.monitor.NullProgressMonitor;
import org.das2.util.monitor.ProgressMonitor;
import org.virbo.datasource.DataSourceEditorPanel;
import org.virbo.datasource.URISplit;

/**
 * Editor panel for getting data from PDS/PPI node.
 * @author jbf
 */
public class PDSPPIDataSourceEditorPanel extends javax.swing.JPanel implements DataSourceEditorPanel {

    private static final Logger logger= LoggerManager.getLogger("apdss.pdsppi");
    
    /**
     * Creates new form PPARAMPPIDataSourceEditorPanel
     */
    public PDSPPIDataSourceEditorPanel() {
        initComponents();
        if ( FileSystem.settings().isOffline() ) {
            JOptionPane.showMessageDialog(this,"internet is not available");
            this.setEnabled(false);
            return;
        }
        updateInventorySoon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        inventoryScComboBox = new javax.swing.JComboBox();
        idComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paramList = new javax.swing.JList();

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("SPACECRAFT:");

        inventoryScComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "voyager", "galileo", "cassini" }));
        inventoryScComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inventoryScComboBoxItemStateChanged(evt);
            }
        });

        idComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Pick...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        paramList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(paramList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inventoryScComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 194, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(idTextField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inventoryScComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String id= idTextField.getText();
            String root= idComboBox.getSelectedItem().toString();
            FileSystem fs= new PDSPPIFileSystem( "/PPI/"+root+"/"+id );
            javax.swing.JTree tree= new javax.swing.JTree( new FSTreeModel(fs) );
            if ( JOptionPane.OK_OPTION==JOptionPane.showConfirmDialog(idComboBox, new JScrollPane(tree) ) ) {
                String ds= tree.getSelectionPath().getLastPathComponent().toString();
                if ( ds.endsWith(".lbl") || ds.endsWith(".LBL") || ds.endsWith(".tab" ) || ds.endsWith(".TAB")  ) {
                    ds= ds.substring(0,ds.length()-4);
                }
                idTextField.setText( ds );
                id= idTextField.getText();
                root= idComboBox.getSelectedItem().toString();
                id= "PPI/"+root+"/"+id;
                updateParamsSoon(id);
            }
        } catch (URISyntaxException ex) {
            Logger.getLogger(PDSPPIDataSourceEditorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * update the paramComboBox later on the event thread.
     * @param dss 
     */
    private void updateParamComboBoxSoon( final Map<String,String> dss ) {
        Runnable run= new Runnable() {
            @Override
            public void run() {
                String[] ss= new String[ dss.size() ];
                ss= dss.keySet().toArray( ss );
                //paramComboBox.setModel( new DefaultComboBoxModel(ss) );
                //paramComboBox.setEnabled(true);
                
                DefaultListModel lm= new DefaultListModel();
                for ( String s: ss ) {
                    lm.addElement(s);
                }
                paramList.setModel( lm );
            }
        };
        SwingUtilities.invokeLater(run);
    }
    
    /**
     * given the new ID, update the available params.
     * @param id 
     */
    private void updateParamsSoon( final String id ) {
        final Map<String,String> dss= PDSPPIDB.getInstance().getParams( id, new NullProgressMonitor() );
        updateParamComboBoxSoon(dss);
        logger.warning("work done on the event thread. TODO: move to its own thread.");
        //Runnable run= new Runnable() {
         //   @Override
         //   public void run() {
         //       final Map<String,String> dss= PDSPPIDB.getInstance().getParams( id, new NullProgressMonitor() );
         //       updateDssComboBoxSoon(dss);
         //   }
        //};
        //new Thread(run).start();
    }
    
    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
            String id= idTextField.getText();
            String root= idComboBox.getSelectedItem().toString();
            id= "PPI/"+root+"/"+id;
            updateParamsSoon(id);
            
            
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void idComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idComboBoxActionPerformed
        idTextField.setText("");
    }//GEN-LAST:event_idComboBoxActionPerformed

    private void inventoryScComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inventoryScComboBoxItemStateChanged
        updateInventorySoon();
    }//GEN-LAST:event_inventoryScComboBoxItemStateChanged

    
    private void updateInventorySoon() {
        Runnable run= new Runnable() {
            @Override
            public void run() {
                try {
                    logger.fine("updateFacetSoon");
                    String sc= String.valueOf(inventoryScComboBox.getSelectedItem());
                    URL url= new URL( String.format( "http://ppi.pds.nasa.gov/ditdos/inventory?sc=%s&facet=SPACECRAFT_NAME&title=%s&o=txt", sc, sc ) );
                    final String[] dss= PDSPPIDB.getInstance().getIds("sc="+sc);
                    Runnable run= new Runnable() { public void run() {
                        idComboBox.setModel( new DefaultComboBoxModel(dss) );
                    } };
                    SwingUtilities.invokeLater(run);
                } catch (MalformedURLException ex) {
                    logger.log(Level.SEVERE, null, ex);
                }
            }   
        };
        new Thread(run).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox idComboBox;
    private javax.swing.JTextField idTextField;
    private javax.swing.JComboBox inventoryScComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList paramList;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean reject(String uri) throws Exception {
        return false;
    }


    
    /**
     * 
     * @param uri
     * @param parent
     * @param mon
     * @return
     * @throws Exception 
     */
    @Override
    public boolean prepare(String uri, Window parent, ProgressMonitor mon) throws Exception {
        return true;
    }

    Map<String,String> params; // hold on to original values for a reference.
    
    @Override
    public void setURI(String uri) {
        URISplit split= URISplit.parse(uri);
        Map<String,String> params= URISplit.parseParams(split.params);
        String sc= params.get(SC);
        if ( sc!=null ) {
            this.inventoryScComboBox.setSelectedItem(sc);
        }
        String id= params.get(ID);
        this.idTextField.setText(id);   
        
    }
    
    public static final String PARAM = "param";
    public static final String ID = "id";
    public static final String SC = "sc";  // spacecraft facet
    
    @Override
    public void markProblems(List<String> problems) {
        
    }

    @Override
    public JPanel getPanel() {
        return this;
    }

    @Override
    public String getURI() {
        String id= "PPI/" + this.idComboBox.getSelectedItem() + "/" + this.idTextField.getText(); //TODO: why must I add PPI??
        String param= this.paramList.getSelectedValue().toString();
        return "vap+pdsppi:" + SC+"="+ inventoryScComboBox.getSelectedItem() + "&" + ID + "="+ id + "&" + PARAM + "="+ param;
    }
    
    public static void main( String[] args ) {
        PDSPPIDataSourceEditorPanel test= new PDSPPIDataSourceEditorPanel();
        JOptionPane.showMessageDialog( null, test);
        System.err.println( test.getURI() );
                
    }
}
