/*
 * JythonScriptPanel.java
 *
 * Created on May 13, 2008, 11:24 AM
 */
package org.virbo.autoplot.scriptconsole;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.das2.util.filesystem.WebFileSystem;
import org.das2.util.monitor.NullProgressMonitor;
import org.virbo.autoplot.ApplicationModel;
import org.virbo.datasource.DataSetSelector;
import org.virbo.datasource.DataSetURL;

/**
 *
 * @author  jbf
 */
public class JythonScriptPanel extends javax.swing.JPanel {

    File file;
    ApplicationModel model;
    DataSetSelector selector;
    
    /** Creates new form JythonScriptPanel */
    public JythonScriptPanel( final ApplicationModel model, final DataSetSelector selector ) {
        initComponents();
        this.model = model;
        this.selector= selector;
        model.addPropertyChangeListener(new PropertyChangeListener() {

            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals(ApplicationModel.PROPERTY_DATASOURCE)) {
                    try {
                        String sfile = model.dataSource().getURL();
                        DataSetURL.URLSplit split = DataSetURL.parse(sfile);
                        if (!(split.file.endsWith(".py") || split.file.endsWith(".jy"))) {
                            return;
                        }
                        file = DataSetURL.getFile( DataSetURL.getURL(sfile), new NullProgressMonitor());
                        StringBuffer buf = new StringBuffer();
                        BufferedReader r = new BufferedReader(new FileReader(file));
                        String s = r.readLine();
                        while (s != null) {
                            buf.append(s + "\n");
                            s = r.readLine();
                        }
                        editorPanel.setText(buf.toString());
                    } catch (IOException ex) {
                        Logger.getLogger(JythonScriptPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorPanel = new javax.swing.JTextPane();
        savePlotButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(editorPanel);

        savePlotButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/virbo/autoplot/go.png"))); // NOI18N
        savePlotButton.setText("save & plot");
        savePlotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePlotButtonActionPerformed(evt);
            }
        });

        saveAsButton.setText("save as...");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });

        jButton1.setText("open...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 444, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(savePlotButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveAsButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(savePlotButton)
                    .add(saveAsButton)
                    .add(jButton1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 261, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {jButton1, saveAsButton, savePlotButton}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents
    private void savePlotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePlotButtonActionPerformed
        try {
            boolean updateSurl = false;
            if (file == null || file.getCanonicalPath().startsWith(WebFileSystem.getDownloadDirectory().toString())) {
                JFileChooser chooser = new JFileChooser();
                int r = chooser.showSaveDialog(this);
                if (r == JFileChooser.APPROVE_OPTION) {
                    file = chooser.getSelectedFile();
                    updateSurl = true;
                }
            }
            OutputStream out = new FileOutputStream(file);
            String text = editorPanel.getText();
            out.write(text.getBytes());
            out.close();
            if (updateSurl) {
                model.setDataSourceURL(file.toString());
            } else {
                if ( model.dataSource()!=null ) model.update();
            }
        } catch (IOException iOException) {
            model.getCanvas().getApplication().getExceptionHandler().handle(iOException);
        }
    }//GEN-LAST:event_savePlotButtonActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
        try {
            boolean updateSurl = false;
            JFileChooser chooser = new JFileChooser();
            if (file != null) {
                chooser.setSelectedFile(file);
            }
            int r = chooser.showSaveDialog(this);
            if (r == JFileChooser.APPROVE_OPTION) {
                file = chooser.getSelectedFile();
                updateSurl = true;
            }
            OutputStream out = new FileOutputStream(file);
            String text = editorPanel.getText();
            out.write(text.getBytes());
            out.close();
            if (updateSurl) {
                model.setDataSourceURL(file.toString());
            } else {
                model.update();
            }
        } catch (IOException iOException) {
            model.getCanvas().getApplication().getExceptionHandler().handle(iOException);
        }        
}//GEN-LAST:event_saveAsButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sfile = selector.getValue();
            DataSetURL.URLSplit split = DataSetURL.parse(sfile);
            if (!(split.file.endsWith(".py") || split.file.endsWith(".jy"))) {
                file = null;
            } else {
                file = DataSetURL.getFile( DataSetURL.getURL(sfile), new NullProgressMonitor());
            }


            JFileChooser chooser = new JFileChooser();
            if (file != null) {
                chooser.setSelectedFile(file);
            }
            int r = chooser.showOpenDialog(this);
            if (r == JFileChooser.APPROVE_OPTION) {
                file = chooser.getSelectedFile();
            }
            BufferedReader read = new BufferedReader(new FileReader(file));
            StringBuffer buf = new StringBuffer();
            String s = read.readLine();
            while (s != null) {
                buf.append(s).append("\n");
                s = read.readLine();
            }

            editorPanel.setText(buf.toString());

        } catch (IOException ex) {
            model.getCanvas().getApplication().getExceptionHandler().handle(ex);
        }           
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane editorPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton savePlotButton;
    // End of variables declaration//GEN-END:variables
}
